//
//  CodeEmitterTests.swift
//  NSAutoAXGeneratorTests
//
//  Tests for the code generation and file emission.
//

import XCTest
@testable import NSAutoAXGenerator

final class CodeEmitterTests: XCTestCase {
    
    var emitter: CodeEmitter!
    var tempDirectory: String!
    
    override func setUp() {
        super.setUp()
        emitter = CodeEmitter(verbose: false)
        
        // Create temporary directory for test outputs
        tempDirectory = NSTemporaryDirectory()
            .appending("NSAutoAXKitTests-\(UUID().uuidString)")
        
        try? FileManager.default.createDirectory(
            atPath: tempDirectory,
            withIntermediateDirectories: true,
            attributes: nil
        )
    }
    
    override func tearDown() {
        super.tearDown()
        
        // Clean up temporary directory
        try? FileManager.default.removeItem(atPath: tempDirectory)
    }
    
    func testGenerateExtensionFile() throws {
        let identifiers = [
            GeneratedIdentifier(ownerType: "TestViewController", propertyName: "titleLabel"),
            GeneratedIdentifier(ownerType: "TestViewController", propertyName: "submitButton")
        ]
        
        let typeDef = TypeDefinition(
            name: "TestViewController",
            sourceFilePath: "/test/TestViewController.swift",
            outlets: [],
            inheritedTypes: ["UIViewController"]
        )
        
        let filesGenerated = try emitter.generateFiles(
            identifiersByType: ["TestViewController": identifiers],
            typeDefinitions: [typeDef],
            outputDirectory: tempDirectory
        )
        
        XCTAssertEqual(filesGenerated, 1)
        
        // Verify file was created
        let expectedFileName = "TestViewController+AutoAX.swift"
        let expectedPath = (tempDirectory as NSString).appendingPathComponent(expectedFileName)
        
        XCTAssertTrue(FileManager.default.fileExists(atPath: expectedPath))
        
        // Read and verify contents
        let contents = try String(contentsOfFile: expectedPath, encoding: .utf8)
        
        XCTAssertTrue(contents.contains("extension TestViewController"))
        XCTAssertTrue(contents.contains("func applyAutoAX()"))
        XCTAssertTrue(contents.contains("titleLabel?.accessibilityIdentifier = \"TestViewController.titleLabel\""))
        XCTAssertTrue(contents.contains("submitButton?.accessibilityIdentifier = \"TestViewController.submitButton\""))
        XCTAssertTrue(contents.contains("swiftlint:disable all"))
        XCTAssertTrue(contents.contains("Auto-generated by NSAutoAXKit"))
    }
    
    func testGenerateMultipleFiles() throws {
        let identifiers1 = [
            GeneratedIdentifier(ownerType: "FirstVC", propertyName: "label")
        ]
        
        let identifiers2 = [
            GeneratedIdentifier(ownerType: "SecondVC", propertyName: "button")
        ]
        
        let typeDef1 = TypeDefinition(
            name: "FirstVC",
            sourceFilePath: "/test/First.swift",
            outlets: [],
            inheritedTypes: ["UIViewController"]
        )
        
        let typeDef2 = TypeDefinition(
            name: "SecondVC",
            sourceFilePath: "/test/Second.swift",
            outlets: [],
            inheritedTypes: ["UIViewController"]
        )
        
        let filesGenerated = try emitter.generateFiles(
            identifiersByType: [
                "FirstVC": identifiers1,
                "SecondVC": identifiers2
            ],
            typeDefinitions: [typeDef1, typeDef2],
            outputDirectory: tempDirectory
        )
        
        XCTAssertEqual(filesGenerated, 2)
        
        // Verify both files exist
        let file1 = (tempDirectory as NSString).appendingPathComponent("FirstVC+AutoAX.swift")
        let file2 = (tempDirectory as NSString).appendingPathComponent("SecondVC+AutoAX.swift")
        
        XCTAssertTrue(FileManager.default.fileExists(atPath: file1))
        XCTAssertTrue(FileManager.default.fileExists(atPath: file2))
    }
    
    func testFileHeaderInformation() throws {
        let identifiers = [
            GeneratedIdentifier(ownerType: "TestVC", propertyName: "label")
        ]
        
        let typeDef = TypeDefinition(
            name: "TestVC",
            sourceFilePath: "/path/to/source/TestVC.swift",
            outlets: [],
            inheritedTypes: ["UIViewController"]
        )
        
        _ = try emitter.generateFiles(
            identifiersByType: ["TestVC": identifiers],
            typeDefinitions: [typeDef],
            outputDirectory: tempDirectory
        )
        
        let filePath = (tempDirectory as NSString).appendingPathComponent("TestVC+AutoAX.swift")
        let contents = try String(contentsOfFile: filePath, encoding: .utf8)
        
        // Verify header contains required information
        XCTAssertTrue(contents.contains("TestVC+AutoAX.swift"))
        XCTAssertTrue(contents.contains("Source: /path/to/source/TestVC.swift"))
        XCTAssertTrue(contents.contains("Generator version:"))
        XCTAssertTrue(contents.contains("import UIKit"))
    }
    
    func testEmptyOutputDirectory() throws {
        let nonExistentDir = tempDirectory.appending("/nested/deep/directory")
        
        let identifiers = [
            GeneratedIdentifier(ownerType: "TestVC", propertyName: "label")
        ]
        
        let typeDef = TypeDefinition(
            name: "TestVC",
            sourceFilePath: "/test/TestVC.swift",
            outlets: [],
            inheritedTypes: ["UIViewController"]
        )
        
        // Should create the directory
        _ = try emitter.generateFiles(
            identifiersByType: ["TestVC": identifiers],
            typeDefinitions: [typeDef],
            outputDirectory: nonExistentDir
        )
        
        XCTAssertTrue(FileManager.default.fileExists(atPath: nonExistentDir))
    }
}

