//
//  CodeEmitter.swift
//  NSAutoAXGenerator
//
//  Generates Swift extension files with applyAutoAX() methods.
//

import Foundation

/// Generates Swift source code files for accessibility identifiers.
struct CodeEmitter {
    
    private let verbose: Bool
    private let version = "1.0.0"
    
    init(verbose: Bool = false) {
        self.verbose = verbose
    }
    
    /// Generates extension files for all types with identifiers.
    ///
    /// - Parameters:
    ///   - identifiersByType: Dictionary mapping type names to their identifiers
    ///   - typeDefinitions: Original type definitions for reference
    ///   - outputDirectory: Directory where files will be written
    /// - Returns: Number of files generated
    /// - Throws: GeneratorError if file writing fails
    func generateFiles(
        identifiersByType: [String: [GeneratedIdentifier]],
        typeDefinitions: [TypeDefinition],
        outputDirectory: String
    ) throws -> Int {
        // Create output directory if needed
        let fileManager = FileManager.default
        if !fileManager.fileExists(atPath: outputDirectory) {
            do {
                try fileManager.createDirectory(
                    atPath: outputDirectory,
                    withIntermediateDirectories: true,
                    attributes: nil
                )
                log("Created output directory: \(outputDirectory)")
            } catch {
                throw GeneratorError.outputDirectoryCreationFailed(outputDirectory)
            }
        }
        
        var filesGenerated = 0
        
        // Create a lookup for type definitions
        let typeDefsByName = Dictionary(
            uniqueKeysWithValues: typeDefinitions.map { ($0.name, $0) }
        )
        
        for (typeName, identifiers) in identifiersByType {
            guard let typeDef = typeDefsByName[typeName] else {
                log("Warning: No type definition found for \(typeName)")
                continue
            }
            
            let fileName = "\(typeName)+AutoAX.swift"
            let filePath = (outputDirectory as NSString).appendingPathComponent(fileName)
            
            let sourceCode = generateExtensionCode(
                for: typeName,
                identifiers: identifiers,
                sourceFile: typeDef.sourceFilePath
            )
            
            do {
                try sourceCode.write(toFile: filePath, atomically: true, encoding: .utf8)
                log("Generated file: \(filePath)")
                filesGenerated += 1
            } catch {
                throw GeneratorError.fileWriteError(error.localizedDescription, path: filePath)
            }
        }
        
        return filesGenerated
    }
    
    /// Generates the Swift code for a type's extension.
    ///
    /// - Parameters:
    ///   - typeName: Name of the type
    ///   - identifiers: Array of identifiers for this type
    ///   - sourceFile: Original source file path
    /// - Returns: Complete Swift source code as string
    private func generateExtensionCode(
        for typeName: String,
        identifiers: [GeneratedIdentifier],
        sourceFile: String
    ) -> String {
        let timestamp = ISO8601DateFormatter().string(from: Date())
        
        var code = """
        //
        // \(typeName)+AutoAX.swift
        // Auto-generated by NSAutoAXKit on \(timestamp)
        //
        // Source: \(sourceFile)
        // Generator version: \(version)
        //
        // This file is auto-generated. Do not edit.
        // swiftlint:disable all
        
        import UIKit
        
        extension \(typeName) {
            
            /// Applies auto-generated accessibility identifiers to all @IBOutlet properties.
            ///
            /// This method is automatically generated by NSAutoAXKit. It assigns deterministic
            /// accessibility identifiers to each outlet for reliable UI testing.
            ///
            /// Call this method from viewDidLoad() or awakeFromNib():
            ///
            /// ```swift
            /// override func viewDidLoad() {
            ///     super.viewDidLoad()
            ///     applyAutoAX()
            /// }
            /// ```
            @objc func applyAutoAX() {
        
        """
        
        // Add identifier assignments
        for identifier in identifiers {
            let safeAccess = identifier.propertyName
            code += "        \(safeAccess)?.accessibilityIdentifier = \"\(identifier.identifier)\"\n"
        }
        
        code += """
            }
        }
        
        """
        
        return code
    }
    
    private func log(_ message: String) {
        guard verbose else { return }
        print("[CodeEmitter] \(message)")
    }
}

